name: dish_detection_api
description: The interface for an API to detect dishes from images.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.9.2 <4.0.0'

dev_dependencies:
  flutter_lints: ^5.0.0
