name: isar_storage_dishes_api
description: A Flutter implementation of the DishesApi that uses isar storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  meta: ^1.8.0
  rxdart: ^0.28.0
  dishes_api:
    path: ../dishes_api

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0