name: dishes_api
description: The interface and models for an API providing access to dishes.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  equatable: ^2.0.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.4.0
  isar_generator: ^3.1.0
  json_serializable: ^6.3.1
  test: ^1.21.4