name: directory_image_storage_api
description: A Flutter implementation of the ImageStorageApi that uses the app directory to store images.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  path: ^1.9.1
  image_storage_api:
    path: ../image_storage_api

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0